# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64326d8fd1cdb79aa31815fc0540daa2bc475b2ad9f3535b73d2f3b681274764623317cd23ca6e5f73b94e3a9094d55cfc5ce4021cd04b8457f43e8bdc5dd6fc

test:
  secret_key_base: 50519578b8af103aafbcc9f3a06e4582accfb9e1b1ea17e06a95a2b42463af651c2b8bddbc1cd59ae4eda2390474cf82c5225cb404649cbb76797797afb17ce1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
